name: TikTokBattle
version: 0.3.0
main: ua.tiktokbattle.TikTokBattle
api-version: '1.20'
author: TikTokBattle
commands:
  spawnmobgren:
    description: Встановити спавн зелених
    permission: battle.admin
  spawnmobpurple:
    description: Встановити спавн фіолетових
    permission: battle.admin
  spawnblockgr:
    description: Встановити ядро зелених
    usage: /spawnblockgr <hp>
    permission: battle.admin
  spawnblockpurple:
    description: Встановити ядро фіолетових
    usage: /spawnblockpurple <hp>
    permission: battle.admin
  battlelane:
    description: Додати або очистити точки маршруту
    usage: /battlelane <green|purple> <1|2|3> <add|clear>
    permission: battle.admin
  battlespawn:
    description: Додати мобів до черги
    usage: /battlespawn <green|purple> <mob> <count>
    permission: battle.admin
  battleboss:
    description: Викликати кастомного боса до черги
    usage: /battleboss <green|purple> <necromancer|witch|poseidon>
    permission: battle.admin
  battlestart:
    permission: battle.admin
  battlestop:
    permission: battle.admin
  battlereset:
    permission: battle.admin
  battlestatus:
    permission: battle.admin
permissions:
  battle.admin:
    default: op
